micronaut:
  application:
    name: uaio-server
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      openapi-explorer:
        paths: classpath:META-INF/swagger/views/openapi-explorer
        mapping: /openapi-explorer/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
datasources:
  default:
    url: jdbc:h2:file:./store/db/data;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
    allow-pool-suspension: true
r2dbc:
  datasources:
    default:
      dialect: H2
      url: r2dbc:h2:file://./store/db/data;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ''
jobrunr:
  background-job-server:
    enabled: false
  dashboard:
    enabled: false
flyway:
  datasources:
    default:
      enabled: true