micronaut:
  application:
    name: uaio-server
datasources:
  default:
    url: jdbc:h2:file:/store/db;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
    allow-pool-suspension: true
r2dbc:
  datasources:
    default:
      dialect: H2
      url: r2dbc:h2:file:///store/db;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ''
jobrunr:
  background-job-server:
    enabled: false
  dashboard:
    enabled: false
flyway:
  datasources:
    default:
      enabled: true
